services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - postgres

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - postgres

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false" # Easiest for local dev, don't do this in prod!
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - postgres

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.1
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
    networks:
      - postgres

  servicereg:
    build: ../service-reg
    container_name: servicereg
    ports:
      - "8761:8761"
    networks:
      - postgres

  configserver:
    build: ../configserver
    container_name: configserver
    ports:
      - "8888:8888"
    depends_on:
      - servicereg
    networks:
      - postgres

  gateway:
    build: ../gateway
    container_name: gateway
    ports:
      - "8084:8084"
    depends_on:
      - servicereg
      - configserver
    networks:
      - postgres

  jobms:
    build: ../jobms
    container_name: jobms
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - servicereg
      - configserver
      - elasticsearch
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - postgres

  companyms:
    build: ../companyms
    container_name: companyms
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - servicereg
      - configserver
      - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - postgres

  reviewms:
    build: ../reviewms
    container_name: reviewms
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - servicereg
      - configserver
      - rabbitmq
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
